version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION}
    container_name: jaeger
    ports:
      - "${DNMP_EXT_HOST_IP:-127.0.0.1}:${JAEGER_OTLP_GRPC_HOST_PORT}:4317"
      - "${DNMP_EXT_HOST_IP:-127.0.0.1}:${JAEGER_OTLP_HTTP_HOST_PORT}:4318"
      - "${DNMP_EXT_HOST_IP:-127.0.0.1}:${JAEGER_UI_HOST_PORT}:16686"
    restart: always
    environment:
      TZ: "$TZ"
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - default
