package main

import (
	"go/ast"
	"os"
	"path/filepath"
	"testing"
)

// TestIsGenerated 约束生成文件标记，go:generate 指令不能让普通源码逃过审计。
func TestIsGenerated(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	generatedPath := filepath.Join(root, "generated.go")
	if err := os.WriteFile(generatedPath, []byte("// Code generated by test. DO NOT EDIT.\npackage sample\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if !isGenerated(generatedPath) {
		t.Fatal("标准生成文件标记应被识别")
	}

	directivePath := filepath.Join(root, "directive.go")
	if err := os.WriteFile(directivePath, []byte("//go:generate stringer -type=Kind\npackage sample\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if isGenerated(directivePath) {
		t.Fatal("go:generate 指令不代表当前文件由工具生成")
	}
}

// TestHasDocRequiresChinese 确保纯英文占位注释不能绕过中文注释规范。
func TestHasDocRequiresChinese(t *testing.T) {
	t.Parallel()

	english := &ast.CommentGroup{List: []*ast.Comment{{Text: "// User describes a user."}}}
	if hasDoc(english, nil) {
		t.Fatal("纯英文注释不应满足中文注释规范")
	}

	chinese := &ast.CommentGroup{List: []*ast.Comment{{Text: "// User 表示业务用户。"}}}
	if !hasDoc(chinese, nil) {
		t.Fatal("包含中文说明的注释应通过")
	}
}
